plugins {
    id 'java'
    id 'application'
    id 'com.diffplug.spotless' version '8.0.0'
}

group = 'catcafe'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'org.example.Main'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
}

test {
    useJUnitPlatform()
}

spotless {
    java {
        googleJavaFormat()
    }
}